name: adhara_markdown_example
description: Minimalistic, highly customizable, regexp based markdown editor and viewer by adhara - Example
version: 0.0.1
author:
homepage:

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhara_markdown:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
